from pathlib import Path

root=Path(__file__).parent; out=root/'packages'; out.mkdir(exist_ok=True)
langs={
'Traditional-Chinese':('繁體中文','steal-an-egg掛機攻略','tw','Steal an egg掛機攻略：偷蛋、孵化與速度養成','Steal an egg掛機攻略, Roblox偷蛋, 寵物孵化, UgPhone雲手機'),
'English':('English','Steal an egg AFK guide','en','Steal an egg AFK Guide: Steal Eggs, Hatch Pets, and Build Speed','Steal an egg AFK guide, Roblox egg stealing, pet hatching, UgPhone'),
'Portuguese':('Portuguese','guia AFK de Steal an egg','pt','Guia AFK de Steal an egg: roube ovos, choque pets e aumente a velocidade','Steal an egg AFK, roubar ovos Roblox, chocar pets, UgPhone'),
'Spanish':('Spanish','guía AFK de Steal an egg','es','Guía AFK de Steal an egg: roba huevos, incuba mascotas y gana velocidad','Steal an egg AFK, robar huevos Roblox, incubar mascotas, UgPhone'),
'Thai':('Thai','คู่มือ AFK Steal an egg','th','คู่มือ AFK Steal an egg: ขโมยไข่ ฟักสัตว์เลี้ยง และเพิ่มความเร็ว','Steal an egg AFK, ขโมยไข่ Roblox, ฟักสัตว์เลี้ยง, UgPhone'),
'Indonesian':('Indonesian','panduan AFK Steal an egg','id','Panduan AFK Steal an egg: curi telur, tetaskan pet, dan tingkatkan kecepatan','Steal an egg AFK, mencuri telur Roblox, menetaskan pet, UgPhone'),
'Vietnamese':('Vietnamese','hướng dẫn AFK Steal an egg','vi','Hướng dẫn AFK Steal an egg: trộm trứng, ấp pet và tăng tốc độ','Steal an egg AFK, trộm trứng Roblox, ấp pet, UgPhone')}

texts={
'English':'''Steal an egg looks simple until a good egg appears far from your base. You must reach it before another player, grab it from the NPC, then escape while the egg owner attacks. Speed is not a cosmetic stat here: it decides which zones you can enter and whether a stolen egg reaches safety. The loop then continues at home, where eggs hatch, pets generate money, and duplicates become upgrades. This **Steal an egg AFK guide** explains the risk-and-reward route, the day-night rhythm, and why treadmill training is a better AFK target than blind clicking. It also shows where UgPhone fits when you want to build speed while your main device stays free.''',
'Portuguese':'''Steal an egg parece simples até aparecer um ovo raro longe da sua base. É preciso chegar antes de outro jogador, pegar o ovo do NPC e escapar enquanto o dono ataca. A velocidade não é apenas um atributo bonito: ela decide quais áreas você consegue visitar e se o ovo roubado chega em segurança. Em casa, o ciclo continua: os ovos chocam, os pets geram dinheiro e as duplicatas viram melhorias. Este **guia AFK de Steal an egg** explica o risco de cada rota, o ritmo de dia e noite e por que treinar na esteira é mais útil do que clicar sem parar. Também mostra onde o UgPhone ajuda quando você quer ganhar velocidade sem deixar o celular principal ocupado.''',
'Spanish':'''Steal an egg parece sencillo hasta que aparece un huevo raro lejos de tu base. Debes llegar antes que otro jugador, tomarlo del NPC y escapar mientras el dueño del huevo te persigue. La velocidad no es un adorno: determina qué zonas puedes visitar y si el huevo robado llega a salvo. En casa, el ciclo continúa: los huevos se incuban, las mascotas producen dinero y los duplicados se convierten en mejoras. Esta **guía AFK de Steal an egg** explica el riesgo de cada ruta, el ritmo entre día y noche y por qué entrenar en la cinta resulta más útil que hacer clic sin rumbo. También muestra cuándo UgPhone puede mantener el entrenamiento activo sin ocupar tu teléfono principal.''',
'Indonesian':'''Steal an egg tampak mudah sampai telur langka muncul jauh dari markas. Kamu harus tiba lebih dulu, mengambil telur dari NPC, lalu kabur saat pemilik telur menyerang. Kecepatan bukan sekadar angka: stat ini menentukan area yang bisa dimasuki dan peluang membawa telur pulang. Di rumah, telur menetas, pet menghasilkan uang, dan duplikat dapat diubah menjadi peningkatan. **Panduan AFK Steal an egg** ini membahas risiko setiap rute, siklus siang-malam, serta alasan treadmill lebih cocok untuk AFK daripada klik membabi buta. UgPhone juga berguna untuk menjaga latihan berjalan tanpa membuat ponsel utama terus menyala.''',
'Vietnamese':'''Steal an egg trông khá đơn giản cho đến khi một quả trứng hiếm xuất hiện ở khu vực xa căn cứ. Bạn phải đến trước người chơi khác, lấy trứng từ NPC rồi chạy về khi chủ trứng tấn công. Tốc độ không chỉ là một chỉ số phụ; nó quyết định khu vực có thể vào và khả năng mang trứng về an toàn. Về nhà, vòng lặp tiếp tục: trứng tự ấp, pet tạo tiền và pet trùng có thể dùng để nâng cấp. **Hướng dẫn AFK Steal an egg** này giải thích rủi ro của từng tuyến, nhịp ngày đêm và vì sao chạy máy chạy bộ phù hợp AFK hơn việc nhấp liên tục. UgPhone giúp duy trì buổi luyện mà không chiếm điện thoại chính.''',
'Traditional-Chinese':'''《Steal an egg》看似簡單，真正遇到稀有蛋時，才會發現速度就是生存條件。你要先趕到NPC旁拿蛋，再在蛋主人攻擊前跑回安全區；途中被追上，這次偷蛋就會失敗。速度不只是面板數字，它決定你能進哪些區域，也影響能否把高品質的蛋帶回家。回到家園後，蛋會自行孵化，寵物負責產錢，多餘寵物可以出售或合成。這篇 **Steal an egg掛機攻略** 會把偷蛋路線、日夜刷新、寵物養成與跑步機AFK一次整理，並說明UgPhone適合放在哪個環節。''',
'Thai':'''Steal an egg ดูเหมือนเล่นง่าย แต่เมื่อไข่หายากเกิดไกลจากฐาน ความเร็วจะกลายเป็นเงื่อนไขสำคัญ คุณต้องไปถึง NPC ก่อนผู้เล่นคนอื่น ขโมยไข่ แล้ววิ่งกลับเขตปลอดภัยขณะที่เจ้าของไข่โจมตี หากถูกจับได้ ไข่จะหลุดมือ ความเร็วจึงกำหนดทั้งพื้นที่ที่เข้าได้และโอกาสนำไข่กลับบ้าน เมื่อกลับถึงบ้าน ไข่จะฟักเอง สัตว์เลี้ยงสร้างเงิน และตัวซ้ำสามารถขายหรือรวมร่างได้ **คู่มือ AFK Steal an egg** นี้รวมเส้นทางขโมย จังหวะกลางวันกลางคืน การเลี้ยงสัตว์ และการฝึกบนลู่วิ่ง พร้อมอธิบายจุดที่ UgPhone ช่วยได้'''}

def body(lang):
 t=texts[lang]; h=langs[lang][1]
 if lang=='English': sections=[('What Is Steal an egg?', 'The game is mainly PVE: eggs belong to NPCs, but players compete to reach them first. Better eggs usually appear farther from safety, and each zone shows a suggested speed. Treat that sign as a checkpoint, not a guarantee.\n\n<!-- SOURCE_IMAGE:1 -->\n\nA successful theft starts beside the egg. Pick it up, turn toward the safe area, and keep the camera pointed along the return route.\n\n<!-- SOURCE_IMAGE:2 -->\n\nFarther zones offer stronger egg pools but leave less room for mistakes.\n\n<!-- SOURCE_IMAGE:3 -->\n\nUse the zone marker to decide when your speed is ready.\n\n<!-- SOURCE_IMAGE:4 -->'),('How the Day-Night Cycle Changes Your Route','Day lasts about five minutes and night about ten seconds. Use daylight to steal. Night is a short reset window for egg pools. When a divine egg is announced, travel to the named zone only if your speed can handle the crowd. Large eggs tend to have better quality, but racing for one can cost more than taking a safe nearby egg.\n\n<!-- SOURCE_IMAGE:5 -->'),('Hatching, Pets, and Home Upgrades','Place stolen eggs at home and wait for their individual hatch timers. Opening is manual, so check back after the timer ends.\n\n<!-- SOURCE_IMAGE:6 -->\n\nUse the one-tap option to equip your strongest pets. They earn money even while you are offline.\n\n<!-- SOURCE_IMAGE:7 -->\n\nUpgrade the home to raise the pet limit and improve steady income.\n\n<!-- SOURCE_IMAGE:8 -->\n\nThe pet guide lists creatures by zone. Completing collections grants money and speed rewards.\n\n<!-- SOURCE_IMAGE:9 -->\n\nSell unwanted pets for cash.\n\n<!-- SOURCE_IMAGE:10 -->\n\nThree matching pets can be combined into a higher tier.\n\n<!-- SOURCE_IMAGE:11 -->'),('Speed Training and AFK Setup','The treadmill is the most reliable AFK target because it directly increases speed. Keep the character running and confirm that the stat rises before leaving the session.\n\n<!-- SOURCE_IMAGE:12 -->\n\nA speed multiplier from the trail shop improves each training tick.\n\n<!-- SOURCE_IMAGE:13 -->\n\nMacros and auto-clickers are a poor fit for stealing: egg quality is random, returning requires camera control and a held run input, and night interrupts the route.\n\n<!-- SOURCE_IMAGE:14 -->'),('How UgPhone Helps','Create a cloud device, install Roblox, open the game, and place the character on the treadmill. Test for several minutes, confirm speed gains, then extend the session. UgPhone reduces phone heat and keeps training separate from your daily device; it does not guarantee rare eggs or replace route decisions.\n\n<!-- SOURCE_IMAGE:15 -->'),('Conclusion','Build speed first, then push into farther zones when the marker matches your stat. Hatch every egg, fill the home with efficient pets, and use short tests to verify AFK gains. For a longer treadmill session without tying up your phone, download UgPhone and try the routine with a free trial.')]
 else: sections=[('遊戲核心', '偷蛋主要是PVE玩法：蛋由NPC持有，玩家比拼到場速度。越遠的區域通常有更好的蛋，但也更容易被追上。區域標示的速度門檻可當作進場參考。\n\n<!-- SOURCE_IMAGE:1 -->\n\n拿到蛋後立即轉向安全區，提前調整鏡頭，避免回程卡住。\n\n<!-- SOURCE_IMAGE:2 -->\n\n遠區的蛋池更好，但失誤成本也更高。\n\n<!-- SOURCE_IMAGE:3 -->\n\n先看區域標示，再決定是否值得冒險。\n\n<!-- SOURCE_IMAGE:4 -->'),('日夜刷新與路線','白天約五分鐘，黑夜約十秒。白天適合偷蛋，黑夜則是等待蛋池刷新。公告出現神聖蛋時，可依速度與人數判斷是否前往；大蛋通常品質較好，但不必為了搶一顆而放棄穩定收益。\n\n<!-- SOURCE_IMAGE:5 -->'),('孵蛋、寵物與家園','把偷來的蛋放回家園，等待各自的孵化時間，時間到後再手動開蛋。\n\n<!-- SOURCE_IMAGE:6 -->\n\n用一鍵功能裝備高品質寵物，離線時也能持續產錢。\n\n<!-- SOURCE_IMAGE:7 -->\n\n升級家園可增加寵物欄位，讓收益更穩定。\n\n<!-- SOURCE_IMAGE:8 -->\n\n寵物指引能查看各區寵物，完成收集可領金錢與速度獎勵。\n\n<!-- SOURCE_IMAGE:9 -->\n\n不要的寵物可出售換錢。\n\n<!-- SOURCE_IMAGE:10 -->\n\n三隻相同寵物可合成更高品階。\n\n<!-- SOURCE_IMAGE:11 -->'),('速度訓練與AFK','跑步機是最適合AFK的目標，因為它直接增加速度。離開前先觀察數分鐘，確認速度確實上升。\n\n<!-- SOURCE_IMAGE:12 -->\n\n蹤跡商店的速度倍速能提高每次訓練收益。\n\n<!-- SOURCE_IMAGE:13 -->\n\n宏指令與連點器不適合偷蛋：蛋品質隨機、回程需要鏡頭控制與長按跑步，黑夜也會打亂流程。\n\n<!-- SOURCE_IMAGE:14 -->'),('UgPhone掛機流程','建立雲手機、安裝Roblox、進入遊戲並把角色放上跑步機。先短測，確認速度增加後再延長時間。UgPhone能減少手機發熱，讓訓練與日常使用分開；它不會保證稀有蛋，也不能取代路線判斷。\n\n<!-- SOURCE_IMAGE:15 -->'),('結語','先養速度，再依區域標示挑戰更遠的蛋。蛋要定時開、寵物要持續更新，AFK則用短測確認收益。想長時間訓練又不想佔用手機，可以下載UgPhone並申請免費試用。')]
 return '\n\n'.join('## '+a+'\n\n'+b for a,b in sections)

for lang,(ol,kw,suf,title,secs) in langs.items():
 slug=kw.replace(' ','-').replace('掛機','afk').replace('攻略','guide').lower()+'-'+suf
 meta=f'- Slug: {slug}\n- SEO Title: {title}\n- Primary Keyword: {kw}\n- Secondary Keywords: {secs}\n- Meta Description: {title}，整理偷蛋、孵化、寵物收益、速度訓練與UgPhone流程。\n- Tags: Steal an egg, Roblox, AFK, Pets, UgPhone\n- Body Length Target: 500-600\n- Output Language: {ol}'
 bodytxt=body(lang)
 plans='\n'.join(f'{i}. Source image {i}\n   - Alt: Steal an egg gameplay image {i}\n   - Purpose: Preserve the matching source visual in its original article context.\n   - Source Image: {i}' for i in range(1,16))
 (out/(lang+'.md')).write_text(f'# {title}\n\n## SEO Metadata\n\n{meta}\n\n## Article Body\n\n{bodytxt}\n\n## Image Plan\n\n{plans}\n',encoding='utf-8')
